# client_tf2vintage.cmake

include("${CMAKE_CURRENT_LIST_DIR}/client_base.cmake")

set(CLIENT_TF2VINTAGE_DIR ${CMAKE_CURRENT_LIST_DIR})

# It's important to include $GAMENAME in the generated_proto directory
# to avoid race conditions when multiple games are in one solution.
set(GENERATED_PROTO_DIR	"${CLIENT_TF2VINTAGE_DIR}/generated_proto_tf")

set(
	CLIENT_TF2VINTAGE_SOURCE_FILES

	# Source Files
	"${CLIENT_TF2VINTAGE_DIR}/c_env_projectedtexture.h"
	"${CLIENT_TF2VINTAGE_DIR}/c_team_objectiveresource.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/c_team_objectiveresource.h"
	"${CLIENT_TF2VINTAGE_DIR}/c_team_train_watcher.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/c_team_train_watcher.h"
	"${CLIENT_TF2VINTAGE_DIR}/hud_voicestatus.cpp"
	"${SRCDIR}/game/shared/teamplay_round_timer.cpp"
	"${SRCDIR}/game/shared/teamplay_round_timer.h"
	"${CLIENT_TF2VINTAGE_DIR}/hud_controlpointicons.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_controlpointicons.h"
	"${CLIENT_TF2VINTAGE_DIR}/voice_menu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_basedeathnotice.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_basedeathnotice.h"
	"${SRCDIR}/game/shared/playerclass_info_parse.cpp"
	"${SRCDIR}/game/shared/playerclass_info_parse.h"
	"${CLIENT_TF2VINTAGE_DIR}/TeamBitmapImage.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_vguiscreencursor.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_base_account.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_base_account.h"
	"${CLIENT_TF2VINTAGE_DIR}/ver_panel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/ver_panel.h"
	"${CLIENT_TF2VINTAGE_DIR}/hud_vote.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/hud_vote.h"
	"${CLIENT_TF2VINTAGE_DIR}/bsp_utils.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/bsp_utils.h"
	"${SRCDIR}/game/shared/bannedwords.cpp"
	"${SRCDIR}/game/shared/bannedwords.h"
	"${SRCDIR}/game/shared/basescriptedweapon.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/basediscordpresence.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/c_lights.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/worldlight.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/worldlight.h"
	"${CLIENT_TF2VINTAGE_DIR}/vis_tester.cpp"
	
	# Header Files
	"${SRCDIR}/game/shared/basescriptedweapon.h"

	# VScript
	"${SRCDIR}/game/shared/vscript_shared.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/vscript_client.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/vscript_client.nut"
	
	# Protobuf Files
	"${SRCDIR}/game/shared/econ/econ_messages.proto"
	
	# Generated Files
	"${GENERATED_PROTO_DIR}/econ_messages.pb.h"
	"${GENERATED_PROTO_DIR}/econ_messages.pb.cc"

	# Discord SDK
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/achievement_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/achievement_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/activity_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/activity_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/application_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/application_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/core.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/core.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/discord.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/event.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/ffi.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/image_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/image_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/lobby_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/lobby_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/network_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/network_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/overlay_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/overlay_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/relationship_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/relationship_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/storage_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/storage_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/store_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/store_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/types.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/types.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/user_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/user_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/voice_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/voice_manager.h"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/achievement_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/activity_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/application_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/core.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/image_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/lobby_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/network_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/overlay_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/relationship_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/storage_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/store_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/types.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/user_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/voice_manager.cpp"

	# game_controls
	"${CLIENT_TF2VINTAGE_DIR}/game_controls/classmenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/game_controls/classmenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/game_controls/buymenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/game_controls/buysubmenu.cpp"

	# Multiplayer
	"${SRCDIR}/game/shared/Multiplayer/multiplayer_animstate.cpp"
	"${SRCDIR}/game/shared/Multiplayer/multiplayer_animstate.h"

	# Econ
	"${SRCDIR}/game/shared/econ/attribute_manager.cpp"
	"${SRCDIR}/game/shared/econ/attribute_manager.h"
	"${SRCDIR}/game/shared/econ/econ_entity.cpp"
	"${SRCDIR}/game/shared/econ/econ_entity.h"
	"${SRCDIR}/game/shared/econ/econ_holidays.cpp"
	"${SRCDIR}/game/shared/econ/econ_holidays.h"
	"${SRCDIR}/game/shared/econ/econ_item_schema.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_schema.h"
	"${SRCDIR}/game/shared/econ/econ_item_system.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_system.h"
	"${SRCDIR}/game/shared/econ/econ_wearable.cpp"
	"${SRCDIR}/game/shared/econ/econ_wearable.h"
	"${SRCDIR}/game/shared/econ/econ_item_view.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_view.h"
	"${SRCDIR}/game/shared/econ/econ_networking.cpp"
	"${SRCDIR}/game/shared/econ/econ_networking.h"
	"${SRCDIR}/game/shared/econ/econ_networking_messages.cpp"
	"${SRCDIR}/game/shared/econ/econ_networking_messages.h"
	"${SRCDIR}/game/shared/econ/econ_item_interface.h"
	"${SRCDIR}/game/shared/econ/game_item_schema.h"
	"${SRCDIR}/game/shared/econ/ihasattributes.h"

	# NextBot
	"${CLIENT_TF2VINTAGE_DIR}/NextBot/c_NextBot.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/NextBot/c_NextBot.h"

	# TF
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_baseobject.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_baseobject.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_entity_currencypack.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_entity_currencypack.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_func_capture_zone.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_func_respawnroom.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_dispenser.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_dispenser.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_sapper.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_sapper.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_sentrygun.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_sentrygun.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_teleporter.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_obj_teleporter.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_playerattachedmodel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_playerattachedmodel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_sdkversionchecker.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_sdkversionchecker.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_ammo_pack.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_deathcallingcard.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_fx.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_fx.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_objective_resource.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_objective_resource.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_player.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_player.h"		
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_playerclass.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_playerresource.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_playerresource.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_particle_ops.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_projectile_rocket.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_projectile_rocket.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_team.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_team.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_weapon_builder.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_weapon_builder.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_vehicle_jeep.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_vehicle_jeep.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/clientmode_tf.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/clientmode_tf.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/econ_notifications.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/econ_notifications.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/teammaterialproxy.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_blood.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_ejectbrass.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_explosions.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_impacts.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_muzzleflash.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_muzzleflash.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_particleeffect.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_taunteffects.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_fx_tracers.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_account.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_ammostatus.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_ammostatus.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_arena_countdown.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_betastamp.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_betastamp.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_bowcharge.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_building_status.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_building_status.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_chat.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_chat.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_crosshair.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_crosshair.h"			
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_damageindicator.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_deathnotice.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_demomancharge.cpp"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_demomanpipes.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_disguise_status.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_distance_meter.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_escort.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_escort.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_flagstatus.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_flagstatus.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_freezepanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_freezepanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_itemeffectmeter.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_inspectpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_inspectpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_mediccallers.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_mediccallers.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_mediccharge.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_engy_build.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_engy_build.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_engy_destroy.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_engy_destroy.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_spy_disguise.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_menu_spy_disguise.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_notification_panel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_notification_panel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_objectivestatus.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_objectivestatus.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_playerstatus.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_playerstatus.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_robot_destruction_status.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_robot_destruction_status.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_scope.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_stalemate.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_statpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_statpanel.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_target_id.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_target_id.h"			
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_teamgoal.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_teamswitch.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_waitingforplayers_panel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_weaponselection.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_winpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_winpanel.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_pve_winpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_pve_winpanel.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_damageaccount_panel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_input_main.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_notificationmanager.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_notificationmanager.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_prediction.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_presence.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_presence.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_steamstats.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_steamstats.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_tips.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_tips.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_viewrender.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_viewrender.h"						
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_viewmodeladdon.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_viewmodeladdon.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_bosshealthmeter.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_bosshealthmeter.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_spymask.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_spymask.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_merasmus_dancer.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_merasmus_bomb_effect.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_merasmus_bomb_effect.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_autorp.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_autorp.h"

	# TF - PvE
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_tf_base_boss.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_tf_base_boss.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_tf_tank_boss.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_mvm_boss_progress_user.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/c_tf_mvm_boss_progress_user.h"
	"${SRCDIR}/game/shared/tf/tf_mann_vs_machine_stats.cpp"
	"${SRCDIR}/game/shared/tf/tf_mann_vs_machine_stats.h"
	"${SRCDIR}/game/shared/tf/tf_upgrades_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_upgrades_shared.h"

	# TF - PvE - Halloween
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_headless_hatman.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_headless_hatman.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_eyeball_boss.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_eyeball_boss.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_merasmus.cpp"

	# TF - Unused
	"${CLIENT_TF2VINTAGE_DIR}/tf/tf_hud_health.cpp"

	# TF - VGUI Controls
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advbutton.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advbutton.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advbuttonbase.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advbuttonbase.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advcheckbutton.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advcheckbutton.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advitembutton.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advitembutton.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advmodelpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advmodelpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advpanellistpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advpanellistpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advslider.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advslider.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advtabs.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_advtabs.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvarcombobox.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvarcombobox.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvarslider.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvarslider.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvartextentry.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvartextentry.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvartogglecheckbutton.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_cvartogglecheckbutton.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_rotatingpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_rotatingpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_scriptobject.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_scriptobject.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_vcontrolslistpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/controls/tf_vcontrolslistpanel.h"

	# TF - VGUI Panels	
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_backgroundpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_backgroundpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_dialogpanelbase.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_dialogpanelbase.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_itemselectionpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_itemselectionpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_itemtooltippanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_itemtooltippanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_loadoutpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_loadoutpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_mainmenupanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_mainmenupanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_menupanelbase.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_menupanelbase.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsadvancedpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsadvancedpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsaudiopanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsaudiopanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsdialog.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsdialog.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionskeyboardpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionskeyboardpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsmousepanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsmousepanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsvideopanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_optionsvideopanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_pausemenupanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_pausemenupanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_tf_upgrades.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/player_vs_environment/c_tf_upgrades.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_tooltippanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_tooltippanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_quitdialogpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_quitdialogpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_shadebackgroundpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_shadebackgroundpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_statsummarydialog.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/panels/tf_statsummarydialog.h"

	# TF - VGUI Unused
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_overview.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_overview.h"	

	# TF - VGUI Panels
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/backgroundpanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/backgroundpanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/ObjectControlPanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/ObjectControlPanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_classmenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_classmenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_clientscoreboard.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_clientscoreboard.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_confirm_dialog.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_confirm_dialog.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_fourteamscoreboard.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_fourteamscoreboard.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_controls.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_controls.h"	
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_imagepanel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_imagepanel.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_intromenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_intromenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mainmenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mainmenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mainmenu_interface.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mainmenu_interface.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mapinfomenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_mapinfomenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_modalstack.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_modalstack.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_roundinfo.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_roundinfo.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_spectatorgui.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_spectatorgui.h"			
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_statsummary.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_statsummary.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_teammenu.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_teammenu.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_textwindow.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_textwindow.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_vgui_video.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_vgui_video.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_viewport.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/tf_viewport.h"		
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/vgui_pda_panel.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/vgui_rootpanel_tf.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/vgui_rootpanel_tf.h"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/vgui_rotation_slider.cpp"
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui/vgui_rotation_slider.h"

	# TF - Shared - Custom Content
	"${SRCDIR}/game/shared/tf/tf_weapon_flaregun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_flaregun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_compound_bow.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_compound_bow.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_jar.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_jar.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_laser_pointer.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_laser_pointer.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox_drink.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox_drink.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_scripted.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_scripted.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_stickbomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_stickbomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat_wood.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat_wood.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_buff_item.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_buff_item.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_sword.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_sword.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_decapitation.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_decapitation.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_flare.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_flare.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_arrow.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_arrow.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_healingbolt.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_healingbolt.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_jar.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_jar.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_stunball.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_stunball.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringe.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringe.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_slap.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_slap.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_crossbow.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_crossbow.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_energyball.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energyball.h"	
	"${SRCDIR}/game/shared/tf/tf_weapon_particlecannon.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_particlecannon.h"	
	"${SRCDIR}/game/shared/tf/tf_projectile_dragons_fury.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_dragons_fury.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_dragons_fury.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_dragons_fury.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_mechanical_arm.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_mechanical_arm.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun_buildingrescue.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energy_ring.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energy_ring.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_raygun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_raygun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketpack.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketpack.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grapplinghook.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grapplinghook.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_defib.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_defib.h"

	# TF - Shared - Classic Content
	"${SRCDIR}/game/shared/tf/tf_weapon_crowbar.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_crowbar.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_chainsaw.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_chainsaw.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_nailgun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_nailgun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_tranq.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_tranq.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_hunterrifle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_hunterrifle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_umbrella.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_umbrella.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_heavyartillery.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_heavyartillery.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_hammerfists.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_hammerfists.h"

	# TF - Shared - Grenades
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenade.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenade.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_caltrop.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_caltrop.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_concussion.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_concussion.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_emp.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_emp.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_gas.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_gas.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_heal.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_heal.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_mirv.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_mirv.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_nail.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_nail.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_napalm.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_napalm.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_smoke_bomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_smoke_bomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_mirv.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_mirv.h"

	# TF - Shared - Base TF2
	"${SRCDIR}/game/shared/tf/tf_weapon_bat.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bonesaw.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bonesaw.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bottle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bottle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_club.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_club.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_fireaxe.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_fireaxe.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_fists.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_fists.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_flamethrower.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_flamethrower.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_pipebomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_pipebomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenadelauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenadelauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_invis.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_invis.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_knife.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_knife.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_medigun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_medigun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_minigun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_minigun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_parse.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_parse.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pda.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pda.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pipebomblauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pipebomblauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pistol.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pistol.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_revolver.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_revolver.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketlauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketlauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shovel.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_shovel.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_smg.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_smg.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_sniperrifle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_sniperrifle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringegun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringegun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_wrench.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_wrench.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenadeproj.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenadeproj.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_gun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_gun.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_melee.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_melee.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_rocket.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_rocket.h"

	# TF - Shared
	"${SRCDIR}/game/shared/tf/achievements_tf.cpp"
	"${SRCDIR}/game/shared/tf/baseobject_shared.cpp"
	"${SRCDIR}/game/shared/tf/baseobject_shared.h"
	"${SRCDIR}/game/shared/tf/entity_bonuspack.cpp"
	"${SRCDIR}/game/shared/tf/entity_bonuspack.h"
	"${SRCDIR}/game/shared/tf/entity_capture_flag.cpp"
	"${SRCDIR}/game/shared/tf/entity_capture_flag.h"
	"${SRCDIR}/game/shared/tf/ihasbuildpoints.h"
	"${SRCDIR}/game/shared/tf/script_parser.cpp"
	"${SRCDIR}/game/shared/tf/script_parser.h"
	"${SRCDIR}/game/shared/tf/tf_fx_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_fx_shared.h"
	"${SRCDIR}/game/shared/tf/tf_gamemovement.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules_vscript.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules.h"
	"${SRCDIR}/game/shared/tf/tf_gamestats_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamestats_shared.h"
	"${SRCDIR}/game/shared/tf/tf_inventory.cpp"
	"${SRCDIR}/game/shared/tf/tf_inventory.h"
	"${SRCDIR}/game/shared/tf/tf_item.cpp"
	"${SRCDIR}/game/shared/tf/tf_item.h"	
	"${SRCDIR}/game/shared/tf/tf_logic_robot_destruction.cpp"
	"${SRCDIR}/game/shared/tf/tf_logic_robot_destruction.h"
	"${SRCDIR}/game/shared/tf/tf_obj_baseupgrade_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_obj_baseupgrade_shared.h"
	"${SRCDIR}/game/shared/tf/tf_player_shared.cpp"	
	"${SRCDIR}/game/shared/tf/tf_player_shared.h"
	"${SRCDIR}/game/shared/tf/tf_playeranimstate.cpp"
	"${SRCDIR}/game/shared/tf/tf_playeranimstate.h"	
	"${SRCDIR}/game/shared/tf/tf_playerclass_info_parse.cpp"
	"${SRCDIR}/game/shared/tf/tf_playerclass_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_playerclass_shared.h"
	"${SRCDIR}/game/shared/tf/tf_powerup_bottle.cpp"
	"${SRCDIR}/game/shared/tf/tf_powerup_bottle.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_base.cpp"	
	"${SRCDIR}/game/shared/tf/tf_projectile_base.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_nail.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_nail.h"
	"${SRCDIR}/game/shared/tf/tf_robot_destruction_robot.cpp"
	"${SRCDIR}/game/shared/tf/tf_robot_destruction_robot.h"
	"${SRCDIR}/game/shared/tf/tf_shareddefs.cpp"
	"${SRCDIR}/game/shared/tf/tf_shareddefs.h"
	"${SRCDIR}/game/shared/tf/tf_usermessages.cpp"
	"${SRCDIR}/game/shared/tf/tf_viewmodel.cpp"
	"${SRCDIR}/game/shared/tf/tf_viewmodel.h"
	"${SRCDIR}/game/shared/tf/tf_wearable.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable.h"
	"${SRCDIR}/game/shared/tf/tf_wearable_demoshield.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable_demoshield.h"
	"${SRCDIR}/game/shared/tf/tf_wearable_razorback.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable_razorback.h"
	"${SRCDIR}/game/shared/tf/entity_bossresource.cpp"
	"${SRCDIR}/game/shared/tf/entity_bossresource.h"
	"${SRCDIR}/game/shared/tf/entity_teleportvortex.cpp"
	"${SRCDIR}/game/shared/tf/entity_teleportvortex.h"
	"${SRCDIR}/game/shared/tf/tf_halloween_boss.cpp"
	"${SRCDIR}/game/shared/tf/tf_halloween_boss.h"
	"${SRCDIR}/game/shared/tf/tf_zombie.cpp"
	"${SRCDIR}/game/shared/tf/tf_zombie.h"
)

set(
	CLIENT_TF2VINTAGE_EXCLUDE_SOURCES
	"${SRCDIR}/game/shared/weapon_parse_default.cpp"
)

set_source_files_properties(
	"${SRCDIR}/common/steamid.cpp"
	"${SRCDIR}/public/rtime.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/achievement_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/activity_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/application_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/core.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/image_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/lobby_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/network_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/overlay_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/relationship_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/storage_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/store_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/types.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/user_manager.cpp"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp/voice_manager.cpp"		
	PROPERTIES SKIP_PRECOMPILE_HEADERS ON
)

add_library(client_tf2vintage MODULE ${CLIENT_TF2VINTAGE_SOURCE_FILES})

set_target_properties(
	client_tf2vintage PROPERTIES
	OUTPUT_NAME "client"
	PREFIX ""
	LIBRARY_OUTPUT_DIRECTORY "${GAMEDIR}/tf2vintage/bin"
)

target_use_client_base(client_tf2vintage CLIENT_TF2VINTAGE_EXCLUDE_SOURCES)

TargetBuildAndAddProto(client_tf2vintage "${SRCDIR}/game/shared/econ/econ_messages.proto" "${GENERATED_PROTO_DIR}")

# Nut
add_custom_command(
	TARGET client_tf2vintage
    PRE_BUILD
    COMMAND ${Python3_EXECUTABLE} "${SRCDIR}/devtools/bin/texttoarray.py" --file "${CLIENT_TF2VINTAGE_DIR}/vscript_client.nut" --name "g_Script_vscript_client" --out "${CLIENT_TF2VINTAGE_DIR}/vscript_client_nut.h"
)

# Copy discord_game_sdk.dll
add_custom_command(
	TARGET client_tf2vintage
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        ${SRCDIR}/thirdparty/discord_game_sdk/lib/x86/discord_game_sdk.dll
        ${LIBRARY_OUTPUT_DIRECTORY}
)

target_link_directories(
	client_tf2vintage PRIVATE

	"${SRCDIR}/thirdparty/discord_game_sdk/lib/x86"
)

target_link_libraries(
	client_tf2vintage PRIVATE

	"${LIBCOMMON}/lzma"
	$<${IS_WINDOWS}:discord_game_sdk.dll>
)

target_include_directories(
	client_tf2vintage PRIVATE
	"${CLIENT_TF2VINTAGE_DIR}/tf/vgui"
	"${CLIENT_TF2VINTAGE_DIR}/tf"
	"${SRCDIR}/game/shared/tf"
	"${SRCDIR}/game/shared/Multiplayer"
	"${SRCDIR}/game/shared/econ"
	"${SRCDIR}/thirdparty/discord_game_sdk/cpp"
)

target_compile_definitions(
	client_tf2vintage PRIVATE
	USES_ECON_ITEMS
	TF_VINTAGE_CLIENT
	GLOWS_ENABLE
)