# server_tf2vintage.cmake

include("${CMAKE_CURRENT_LIST_DIR}/server_base.cmake")

if (${IS_SOURCESDK})
	include("${CMAKE_CURRENT_LIST_DIR}/nav_mesh.cmake")
endif()

# It's important to include $GAMENAME in the generated_proto directory
# to avoid race conditions when multiple games are in one solution.
set(GENERATED_PROTO_DIR	"${SERVER_TF2VINTAGE_DIR}/generated_proto_tf")

set(SERVER_TF2VINTAGE_DIR ${CMAKE_CURRENT_LIST_DIR})
set(
	SERVER_TF2VINTAGE_SOURCE_FILES

	"${SERVER_TF2VINTAGE_DIR}/env_projectedtexture.h"
	"${SERVER_TF2VINTAGE_DIR}/ai_relationship.cpp"
	"${SERVER_TF2VINTAGE_DIR}/basegrenade_concussion.cpp"
	"${SERVER_TF2VINTAGE_DIR}/basegrenade_contact.cpp"
	"${SERVER_TF2VINTAGE_DIR}/basegrenade_timed.cpp"
	"${SERVER_TF2VINTAGE_DIR}/EntityFlame.h"
	"${SERVER_TF2VINTAGE_DIR}/hl2/Func_Monitor.cpp"
	"${SERVER_TF2VINTAGE_DIR}/grenadethrown.cpp"
	"${SERVER_TF2VINTAGE_DIR}/grenadethrown.h"
	"${SERVER_TF2VINTAGE_DIR}/monstermaker.cpp"
	"${SERVER_TF2VINTAGE_DIR}/monstermaker.h"
	"${SERVER_TF2VINTAGE_DIR}/physics_bone_follower.h"
	"${SRCDIR}/game/shared/ragdoll_shared.h"
	"${SRCDIR}/game/shared/solidsetdefaults.h"
	"${SRCDIR}/game/shared/hl2/survival_gamerules.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_objectiveresource.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_objectiveresource.h"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point.h"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point_master.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point_master.h"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point_round.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_control_point_round.h"
	"${SERVER_TF2VINTAGE_DIR}/team_train_watcher.cpp"
	"${SERVER_TF2VINTAGE_DIR}/team_train_watcher.h"
	"${SRCDIR}/game/shared/teamplayroundbased_gamerules.cpp"
	"${SRCDIR}/game/shared/touchlink.h"
	"${SERVER_TF2VINTAGE_DIR}/trigger_area_capture.cpp"
	"${SERVER_TF2VINTAGE_DIR}/trigger_area_capture.h"
	"${SRCDIR}/game/shared/teamplay_round_timer.cpp"
	"${SRCDIR}/game/shared/teamplay_round_timer.h"
	"${SRCDIR}/game/shared/playerclass_info_parse.cpp"
	"${SRCDIR}/game/shared/playerclass_info_parse.h"
	"${SERVER_TF2VINTAGE_DIR}/ScriptGameEventListener.cpp"
	"${SERVER_TF2VINTAGE_DIR}/ScriptGameEventListener.h"
	"${SERVER_TF2VINTAGE_DIR}/netpropmanager.cpp"
	"${SERVER_TF2VINTAGE_DIR}/netpropmanager.h"
	"${SRCDIR}/game/shared/bannedwords.cpp"
	"${SRCDIR}/game/shared/bannedwords.h"
	"${SRCDIR}/game/shared/basescriptedweapon.cpp"
	"${SRCDIR}/game/shared/basescriptedweapon.h"

	# VScript
	"${SRCDIR}/game/shared/vscript_shared.cpp"
	"${SERVER_TF2VINTAGE_DIR}/vscript_server.cpp"
	"${SERVER_TF2VINTAGE_DIR}/vscript_server.nut"
	"${SRCDIR}/game/shared/vscript_consts_shared.cpp"
	"${SRCDIR}/game/shared/vscript_consts_weapons.cpp"
	"${SRCDIR}/game/shared/vscript_funcs_shared.cpp"
	"${SRCDIR}/game/shared/vscript_singletons.cpp"
	"${SRCDIR}/game/shared/logic_script_client.cpp"
	"${SRCDIR}/game/shared/matchers.cpp"
	
	# Protobuf Files
	"${SRCDIR}/game/shared/econ/econ_messages.proto"
	
	# Generated Files
	"${GENERATED_PROTO_DIR}/econ_messages.pb.h"
	"${GENERATED_PROTO_DIR}/econ_messages.pb.cc"

	# Multiplayer
	"${SRCDIR}/game/shared/Multiplayer/multiplayer_animstate.cpp"
	"${SRCDIR}/game/shared/Multiplayer/multiplayer_animstate.h"

	# Econ
	"${SRCDIR}/game/shared/econ/attribute_manager.cpp"
	"${SRCDIR}/game/shared/econ/attribute_manager.h"
	"${SRCDIR}/game/shared/econ/econ_entity.cpp"
	"${SRCDIR}/game/shared/econ/econ_entity.h"
	"${SRCDIR}/game/shared/econ/econ_holidays.cpp"
	"${SRCDIR}/game/shared/econ/econ_holidays.h"
	"${SRCDIR}/game/shared/econ/econ_item_schema.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_schema.h"
	"${SRCDIR}/game/shared/econ/econ_item_system.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_system.h"
	"${SRCDIR}/game/shared/econ/econ_wearable.cpp"
	"${SRCDIR}/game/shared/econ/econ_wearable.h"
	"${SRCDIR}/game/shared/econ/econ_item_view.cpp"
	"${SRCDIR}/game/shared/econ/econ_item_view.h"
	"${SRCDIR}/game/shared/econ/econ_networking.cpp"
	"${SRCDIR}/game/shared/econ/econ_networking.h"
	"${SRCDIR}/game/shared/econ/econ_networking_messages.cpp"
	"${SRCDIR}/game/shared/econ/econ_networking_messages.h"
	"${SRCDIR}/game/shared/econ/econ_item_interface.h"
	"${SRCDIR}/game/shared/econ/game_item_schema.h"
	"${SRCDIR}/game/shared/econ/ihasattributes.h"

	# NextBot
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBot.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBot.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotBehavior.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotBodyInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotBodyInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotComponentInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotComponentInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotContextualQueryInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotDebug.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotEventResponderInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotGroundLocomotion.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotGroundLocomotion.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotIntentionInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotIntentionInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotKnownEntity.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotLocomotionInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotLocomotionInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotManager.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotManager.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotUtil.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotVisionInterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NextBotVisionInterface.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/simple_bot.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/simple_bot.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NavMeshEntities/func_nav_prerequisite.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/NavMeshEntities/func_nav_prerequisite.h"

	# NextBot - Path
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotChasePath.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotChasePath.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotPath.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotPath.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotPathFollow.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotPathFollow.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Path/NextBotRetreatPath.h"

	# NextBot - Player
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayer.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayer.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayerBody.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayerBody.h"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayerLocomotion.cpp"
	"${SERVER_TF2VINTAGE_DIR}/NextBot/Player/NextBotPlayerLocomotion.h"

	# TF
	# TF - Nav Mesh
	"${SERVER_TF2VINTAGE_DIR}/tf/nav_mesh/tf_nav_area.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/nav_mesh/tf_nav_area.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/nav_mesh/tf_nav_mesh.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/nav_mesh/tf_nav_mesh.h"

	"${SERVER_TF2VINTAGE_DIR}/tf/entity_ammopack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_ammopack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_armor.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_armor.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_currencypack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_currencypack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_forcerespawn.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_forcerespawn.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_game_text_tf.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_healthkit.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_healthkit.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_intermission.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_intermission.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_roundwin.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_roundwin.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_tfstart.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_tfstart.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_player_equip.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_wheelofdoom.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_wheelofdoom.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_capture_zone.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_capture_zone.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/func_changeclass.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_changeclass.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_no_build.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_no_build.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_nogrenades.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_nogrenades.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_regenerate.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_regenerate.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/func_respawnroom.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_respawnroom.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/te_tfblood.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/te_tfblood.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_ammo_pack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_ammo_pack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_bot_temp.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_bot_temp.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_client.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_client.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_eventlog.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_filters.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_fx.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_fx.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_gameinterface.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_gamestats.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_gamestats.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_hltvdirector.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_logic_entities.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_logic_entities.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_dispenser.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_dispenser.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_sapper.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_sapper.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_sentrygun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_sentrygun.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_teleporter.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_obj_teleporter.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_objective_resource.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_objective_resource.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_player.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_player.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_player_resource.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_player_resource.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_playerclass.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_playerclass.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_playermove.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_powerup.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_powerup.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_projectile_rocket.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_projectile_rocket.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_team.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_team.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_turret.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_turret.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_voteissues.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_voteissues.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_weapon_builder.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_weapon_builder.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/func_respawnflag.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_respawnflag.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/func_flagdetectionzone.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/func_flagdetectionzone.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_vehicle_jeep.cpp"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_generic_bomb.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_generic_bomb.h"	
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_pushentity.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_pushentity.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/trigger_stun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/trigger_stun.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/trigger_addcondition.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_spawn_manager.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_spawn_manager.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_merasmus_trickortreatprop.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_merasmus_trickortreatprop.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_soldier_statue.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_soldier_statue.h"

	# TF - Unused
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_grenadepack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/entity_grenadepack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_mapitems.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_mapitems.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_timer.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/tf_timer.h"

	# TF - PvE
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/map_entities/tf_upgrades.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/map_entities/tf_upgrades.h"
	"${SRCDIR}/game/shared/tf/tf_upgrades_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_upgrades_shared.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_mann_vs_machine_logic.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_mann_vs_machine_logic.h"
	"${SRCDIR}/game/shared/tf/tf_mann_vs_machine_stats.cpp"
	"${SRCDIR}/game/shared/tf/tf_mann_vs_machine_stats.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_population_manager.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_population_manager.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_populators.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_populators.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_populator_spawners.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_populator_spawners.h"

	# TF - NPCs
	# TF - NPCs - Halloween
	# TF - NPCs - Halloween - Headless Hatman
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman.h"

	# Behavior
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_behavior.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_dying.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_dying.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_emerge.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_emerge.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_terrify.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/headless_hatman_terrify.h"

	# Eyeball Boss
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss.h"

	# Behavior
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_approach.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_approach.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_behavior.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_dead.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_dead.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_emerge.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_emerge.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_emote.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_emote.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_escape.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_escape.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_idle.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_idle.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_notice.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_notice.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_rockets.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_rockets.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_stun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_stun.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_teleport.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/eyeball_boss_teleport.h"

	# Merasmus
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_components.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_components.h"

	# Behavior
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_aoeattack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_aoeattack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_behavior.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_disguise.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_disguise.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_dying.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_dying.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_escape.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_escape.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_reveal.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_reveal.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_staffattack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_staffattack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_stunned.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_stunned.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_taunt.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_taunt.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_teleport.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_teleport.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_throwinggrenade.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_throwinggrenade.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_zap.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/merasmus_zap.h"

	# Zombie
	"${SRCDIR}/game/shared/tf/tf_zombie.cpp"
	"${SRCDIR}/game/shared/tf/tf_zombie.h"

	# Behavior
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_behavior.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_spawn.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_spawn.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_special_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/zombie_special_attack.h"

	"${SRCDIR}/game/shared/tf/tf_halloween_boss.cpp"
	"${SRCDIR}/game/shared/tf/tf_halloween_boss.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/ghost.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/ghost.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/ghost_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/ghost_behavior.h"

	# Robots
	# Tank
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_tank_boss.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_tank_boss.h"

	# Boss
	# Grunt
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_base_boss.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_base_boss.h"

	"${SRCDIR}/game/shared/tf/tf_robot_destruction_robot.cpp"
	"${SRCDIR}/game/shared/tf/tf_robot_destruction_robot.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_robot_destruction_robot_behaviors.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/player_vs_environment/tf_robot_destruction_robot_behaviors.h"

	# Shared
	# Weapons
	# Custom Content
	"${SRCDIR}/game/shared/tf/tf_weapon_flaregun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_flaregun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_compound_bow.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_compound_bow.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_jar.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_jar.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_laser_pointer.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_laser_pointer.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox_drink.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_lunchbox_drink.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_scripted.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_scripted.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_stickbomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_stickbomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat_wood.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat_wood.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_buff_item.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_buff_item.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_sword.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_sword.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_decapitation.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_decapitation.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_flare.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_flare.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_arrow.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_arrow.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_healingbolt.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_healingbolt.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_jar.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_jar.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_stunball.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_stunball.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringe.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringe.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_slap.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_slap.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_crossbow.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_crossbow.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_energyball.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energyball.h"	
	"${SRCDIR}/game/shared/tf/tf_weapon_particlecannon.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_particlecannon.h"	
	"${SRCDIR}/game/shared/tf/tf_projectile_dragons_fury.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_dragons_fury.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_dragons_fury.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_dragons_fury.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_mechanical_arm.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_mechanical_arm.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun_buildingrescue.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energy_ring.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_energy_ring.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_raygun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_raygun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketpack.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketpack.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grapplinghook.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grapplinghook.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_defib.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_defib.h"	

	# Classic Content
	"${SRCDIR}/game/shared/tf/tf_weapon_crowbar.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_crowbar.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_chainsaw.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_chainsaw.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_nailgun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_nailgun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_tranq.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_tranq.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_hunterrifle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_hunterrifle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_umbrella.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_umbrella.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_heavyartillery.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_heavyartillery.h"		
	"${SRCDIR}/game/shared/tf/tf_weapon_hammerfists.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_hammerfists.h"	

	# Grenades
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenade.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenade.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_caltrop.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_caltrop.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_concussion.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_concussion.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_emp.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_emp.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_gas.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_gas.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_heal.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_heal.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_mirv.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_mirv.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_nail.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_nail.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_napalm.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_napalm.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_smoke_bomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_smoke_bomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_mirv.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_mirv.h"

	# Base TF2
	"${SRCDIR}/game/shared/tf/tf_weapon_bat.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bat.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bonesaw.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bonesaw.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_bottle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_bottle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_club.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_club.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_fireaxe.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_fireaxe.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_fists.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_fists.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_flamethrower.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_flamethrower.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_pipebomb.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenade_pipebomb.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenadelauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_grenadelauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_invis.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_invis.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_knife.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_knife.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_medigun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_medigun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_minigun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_minigun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_parse.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_parse.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pda.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pda.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pipebomblauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pipebomblauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_pistol.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_pistol.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_revolver.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_revolver.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketlauncher.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_rocketlauncher.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_shotgun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_shovel.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_shovel.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_smg.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_smg.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_sniperrifle.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_sniperrifle.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringegun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_syringegun.h"
	"${SRCDIR}/game/shared/tf/tf_weapon_wrench.cpp"
	"${SRCDIR}/game/shared/tf/tf_weapon_wrench.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenadeproj.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_grenadeproj.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_gun.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_gun.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_melee.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_melee.h"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_rocket.cpp"
	"${SRCDIR}/game/shared/tf/tf_weaponbase_rocket.h"
	
	"${SRCDIR}/game/shared/tf/achievements_tf.cpp"
	"${SRCDIR}/game/shared/tf/baseobject_shared.cpp"
	"${SRCDIR}/game/shared/tf/baseobject_shared.h"
	"${SRCDIR}/game/shared/tf/entity_bonuspack.cpp"
	"${SRCDIR}/game/shared/tf/entity_bonuspack.h"
	"${SRCDIR}/game/shared/tf/entity_bossresource.cpp"
	"${SRCDIR}/game/shared/tf/entity_bossresource.h"
	"${SRCDIR}/game/shared/tf/entity_capture_flag.cpp"
	"${SRCDIR}/game/shared/tf/entity_capture_flag.h"
	"${SRCDIR}/game/shared/tf/entity_teleportvortex.cpp"
	"${SRCDIR}/game/shared/tf/entity_teleportvortex.h"
	"${SRCDIR}/game/shared/tf/ihasbuildpoints.h"
	"${SRCDIR}/game/shared/tf/script_parser.cpp"
	"${SRCDIR}/game/shared/tf/script_parser.h"
	"${SRCDIR}/game/shared/tf/tf_fx_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_fx_shared.h"
	"${SRCDIR}/game/shared/tf/tf_gamemovement.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules_vscript.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamerules.h"
	"${SRCDIR}/game/shared/tf/tf_gamestats_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_gamestats_shared.h"
	"${SRCDIR}/game/shared/tf/tf_inventory.cpp"
	"${SRCDIR}/game/shared/tf/tf_inventory.h"
	"${SRCDIR}/game/shared/tf/tf_item.cpp"
	"${SRCDIR}/game/shared/tf/tf_item.h"	
	"${SRCDIR}/game/shared/tf/tf_logic_robot_destruction.cpp"
	"${SRCDIR}/game/shared/tf/tf_logic_robot_destruction.h"
	"${SRCDIR}/game/shared/tf/tf_obj_baseupgrade_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_obj_baseupgrade_shared.h"
	"${SRCDIR}/game/shared/tf/tf_player_shared.cpp"	
	"${SRCDIR}/game/shared/tf/tf_player_shared.h"
	"${SRCDIR}/game/shared/tf/tf_playeranimstate.cpp"
	"${SRCDIR}/game/shared/tf/tf_playeranimstate.h"	
	"${SRCDIR}/game/shared/tf/tf_playerclass_info_parse.cpp"
	"${SRCDIR}/game/shared/tf/tf_playerclass_shared.cpp"
	"${SRCDIR}/game/shared/tf/tf_playerclass_shared.h"
	"${SRCDIR}/game/shared/tf/tf_powerup_bottle.cpp"
	"${SRCDIR}/game/shared/tf/tf_powerup_bottle.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_base.cpp"	
	"${SRCDIR}/game/shared/tf/tf_projectile_base.h"
	"${SRCDIR}/game/shared/tf/tf_projectile_nail.cpp"
	"${SRCDIR}/game/shared/tf/tf_projectile_nail.h"
	"${SRCDIR}/game/shared/tf/tf_shareddefs.cpp"
	"${SRCDIR}/game/shared/tf/tf_shareddefs.h"
	"${SRCDIR}/game/shared/tf/tf_usermessages.cpp"	
	"${SRCDIR}/game/shared/tf/tf_viewmodel.cpp"
	"${SRCDIR}/game/shared/tf/tf_viewmodel.h"
	"${SRCDIR}/game/shared/tf/tf_wearable.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable.h"
	"${SRCDIR}/game/shared/tf/tf_wearable_demoshield.h"
	"${SRCDIR}/game/shared/tf/tf_wearable_demoshield.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable_razorback.cpp"
	"${SRCDIR}/game/shared/tf/tf_wearable_razorback.h"

	# Bots
	# Behaviors
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_behavior.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_behavior.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_escort.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_escort.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/squad/tf_bot_escort_squad_leader.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/squad/tf_bot_escort_squad_leader.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_tactical_monitor.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_tactical_monitor.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_scenario_monitor.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_scenario_monitor.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_seek_and_destroy.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_seek_and_destroy.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_retreat_to_cover.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_retreat_to_cover.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_roam.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_roam.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_melee_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_melee_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_approach_object.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_approach_object.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_get_health.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_get_health.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_get_ammo.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_get_ammo.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_dead.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_dead.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_move_to_vantage_point.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_move_to_vantage_point.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_mvm_deploy_bomb.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_mvm_deploy_bomb.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_taunt.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_taunt.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_use_teleporter.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_use_teleporter.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_destroy_enemy_sentry.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_destroy_enemy_sentry.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_use_item.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/tf_bot_use_item.h"

	# Missions
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_destroy_sentries.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_destroy_sentries.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_reprogrammed.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_reprogrammed.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_suicide_bomber.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/missions/tf_bot_mission_suicide_bomber.h"

	# Scenarios
	# Capture Point
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_capture_point.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_capture_point.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point_block_capture.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point_block_capture.h"

	# Payload
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_push.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_push.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_block.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_block.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_guard.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/payload/tf_bot_payload_guard.h"

	# Capture The Flag
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_fetch_flag.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_fetch_flag.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_deliver_flag.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_deliver_flag.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_escort_flag_carrier.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_escort_flag_carrier.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_attack_flag_defenders.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/scenario/capture_the_flag/tf_bot_attack_flag_defenders.h"
	
	# Engineer
	# MvM
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_sentry.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_sentry.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_teleporter.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_teleporter.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_idle.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_idle.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_teleport_spawn.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_teleport_spawn.h"

	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_move_to_build.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_move_to_build.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_entrance.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_entrance.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_exit.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_exit.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_sentrygun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_sentrygun.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_dispenser.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_build_dispenser.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_building.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/engineer/tf_bot_engineer_building.h"

	# Medic
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/medic/tf_bot_medic_heal.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/medic/tf_bot_medic_heal.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/medic/tf_bot_medic_retreat.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/medic/tf_bot_medic_retreat.h"

	# Sniper
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/sniper/tf_bot_sniper_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/sniper/tf_bot_sniper_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/sniper/tf_bot_sniper_lurk.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/sniper/tf_bot_sniper_lurk.h"

	# Spy
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_infiltrate.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_infiltrate.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_sap.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_sap.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_attack.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_attack.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_leave_spawn_room.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_leave_spawn_room.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_lurk.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_lurk.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_hide.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/spy/tf_bot_spy_hide.h"

	# Demoman
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/demoman/tf_bot_prepare_stickybomb_trap.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/demoman/tf_bot_prepare_stickybomb_trap.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/demoman/tf_bot_stickybomb_sentrygun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/demoman/tf_bot_stickybomb_sentrygun.h"

	# Nav Entities
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_move_to.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_move_to.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_wait.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_wait.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_destroy_entity.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/behavior/nav_entities/tf_bot_nav_ent_destroy_entity.h"

	# TF - Map Entities
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_engineer_nest.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_engineer_nest.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_sentrygun.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_sentrygun.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_teleexit.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_teleexit.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_entity.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint_entity.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_bot_roster.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_bot_roster.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/map_entities/tf_hint.h"

	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_components.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_components.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_manager.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_manager.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_squad.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_bot_squad.h"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_path_follower.cpp"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot/tf_path_follower.h"
)

set(
	SERVER_TF2VINTAGE_EXCLUDE_SOURCES
)

set_source_files_properties(
	"${SRCDIR}/common/steamid.cpp"
	"${SRCDIR}/public/rtime.cpp"	
	PROPERTIES SKIP_PRECOMPILE_HEADERS ON
)

add_library(server_tf2vintage MODULE ${SERVER_TF2VINTAGE_SOURCE_FILES})

set_target_properties(
	server_tf2vintage PROPERTIES
	OUTPUT_NAME "server"
	PREFIX ""
	LIBRARY_OUTPUT_DIRECTORY "${GAMEDIR}/tf2vintage/bin"
)

target_use_server_base(server_tf2vintage SERVER_TF2VINTAGE_EXCLUDE_SOURCES)

TargetBuildAndAddProto(server_tf2vintage ${SRCDIR}/game/shared/econ/econ_messages.proto "${GENERATED_PROTO_DIR}")

# Nut
add_custom_command(
	TARGET client_tf2vintage
    PRE_BUILD
    COMMAND ${Python3_EXECUTABLE} "${SRCDIR}/devtools/bin/texttoarray.py" --file "${SERVER_TF2VINTAGE_DIR}/vscript_server.nut" --name "g_Script_vscript_server" --out "${SERVER_TF2VINTAGE_DIR}/vscript_server_nut.h"
)

target_link_libraries(
	server_tf2vintage PRIVATE

	"${LIBCOMMON}/lzma"
)

target_include_directories(
	server_tf2vintage PRIVATE
	"${SRCDIR}/game/shared/tf"
	"${SERVER_TF2VINTAGE_DIR}/tf"
	"${SERVER_TF2VINTAGE_DIR}/tf/bot"
	"${SRCDIR}/game/shared/Multiplayer"
	"${SRCDIR}/game/shared/econ"
)

target_compile_definitions(
	server_tf2vintage PRIVATE
	USES_ECON_ITEMS
	TF_VINTAGE
	GLOWS_ENABLE
	NEXT_BOT
)

if (${IS_SOURCESDK})
	target_use_nav_mesh(server_tf2vintage)
endif()